from distutils.core import setup

setup(
    name="turterra",
    version="1.0",
    authors=["Barbara Terlouw", "Janani Durairaj"],
    packages=[
        "turterra",
        "turterra/utils",
        "turterra/dependencies",
        "turterra/dependencies/pikachu",
        "turterra/dependencies/modeller",
    ],
    python_requires="==3.9.*",
    install_requires=[
        "numpy",
        "numba",
        "scipy",
        "prody",
        "biopython",
        "typer",
        "pyparsing",
        "dash==2.0.0",
        "dash-bio==1.0.1",
        "dash-daq==0.5.0",
        "dash-bio-utils==0.0.6",
        "cryptography",
        "dash-cytoscape==0.3.0",
        "dash-extensions==0.0.67",
        "matplotlib",
        "pandas",
    ],
    extras_require={"model": ["modeller",]},
    scripts=["bin/turterra", "bin/turterra-build"],
)
